# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

ruby '3.0.0'

gem 'byebug'
gem 'dry-monads'
gem 'gush'

# gem 'dwf', '~> 0.1.12'
gem 'nokogiri', '~> 1.13', '>= 1.13.8'
gem 'rails'
gem 'sinatra'
